# 数据源配置
# hikari数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # 主库数据源
    master:
      jdbc-url: jdbc:mysql://localhost:3306/newbee_mall_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
      pool-name: hikariCP
      minimum-idle: 100
      maximum-pool-size: 200
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 1000
      password:
      client-type: lettuce
      lettuce:
        pool:
          enabled: true
      jedis:
        pool:
          max-active: 5
          max-idle: 10
          min-idle: 10
          max-wait: 3000
